spring:
  data:
    mongodb:
      host: localhost
      port: 5435
      authenticationDatabase: admin
      username: root
      password: '1234'
      database: examples
jwt:
  secret: p5bNe3sgQ6tV9nGXXtiRWJZSYvuOnnf4UsR7q7bltJg=